name = "OffsetTables"
uuid = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "0.0.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
RegressionTests = "2cca1867-674a-4323-b559-fc77c0bbdb31"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "RegressionTests", "Test"]
