name = "OffsetTables"
uuid = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "0.0.0"

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
